name: develop

# Controls when the workflow will run
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  STAGING_ENV_FILE: ${{secrets.DEV_ENV_FILE}}

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
          node-version: [22.X]
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node-version }}

        - run: |
            echo "$STAGING_ENV_FILE" >> .env
            yarn install --frozen-lockfile
            yarn lint
            yarn build
          shell: bash

